CREATE DATABASE IF NOT EXISTS hallbooking_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hallbooking_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
